#!/usr/bin/env node
// Checks that blog translations are structurally complete — no dropped
// section, no changed link, no untranslated title, the product name intact.
//
// Translations are no longer generated by this script (ut-docs#2293). Since
// ut-docs#2291, the cycle's own model (Claude or Codex, whichever is running
// the Dev step) writes translated posts directly into
// src/content/blog/<locale>/, following the checklist in
// `ut-docs/reference/translation.md`, and commits them like any other
// content. This script is the automated half of that checklist: a pure,
// no-network structural check over whatever is already committed, run after
// the fact rather than generating anything. Because it makes no network
// call, it can run in GitHub-hosted CI, unlike the Ollama-backed generator
// this replaces.
//
// English posts live in src/content/blog/en-gb/ and are the source of
// truth (that is the folder the CMS files into). A missing translation is
// not an error — the site falls back to English and says so — so this
// script only checks locales that already have a file for a given post.
//
//   node scripts/translate-posts.js                       # check everything
//   node scripts/translate-posts.js --locale de-de
//   node scripts/translate-posts.js --slug whats-new-v0-2-70
import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.join(__dirname, "..");
const BLOG = path.join(ROOT, "src", "content", "blog");
const SOURCE_LOCALE = "en-gb";

// Named in the target language's own terms. Kept from the old generator:
// still the set of locales this checker knows to look for, and verify()
// still needs `audience`-free `language`/script expectations per locale.
const LOCALES = {
  "tr-tr": { language: "Turkish (Türkçe)", audience: "shop owners in Turkey" },
  "zh-cn": { language: "Simplified Chinese (简体中文)", audience: "shop owners in China" },
  "fa-ir": { language: "Persian/Farsi (فارسی)", audience: "shop owners in Iran" },
  "de-de": { language: "German (Deutsch)", audience: "shop owners in Germany" },
};

const args = process.argv.slice(2);
const only = (flag) => {
  const i = args.indexOf(flag);
  return i === -1 ? null : args[i + 1];
};
const onlyLocale = only("--locale");
const onlySlug = only("--slug");

function splitFrontmatter(raw) {
  const match = raw.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/);
  if (!match) throw new Error("post has no frontmatter");
  return { frontmatter: match[1], body: match[2] };
}

function field(frontmatter, name) {
  const m = frontmatter.match(new RegExp(`^${name}:\\s*(.*)$`, "m"));
  return m ? m[1].trim().replace(/^"(.*)"$/, "$1") : null;
}

// Cheap structural checks. A mistranslation reads fine and is a judgement
// call; a DROPPED section or a rewritten URL is a defect, and both are things
// a model does quietly when it decides to summarise.
function verify(source, translated, locale) {
  const problems = [];
  const headings = (s) => (s.match(/^#{1,6} /gm) || []).length;
  if (headings(translated.body) !== headings(source.body)) {
    problems.push(
      `heading count ${headings(translated.body)} != ${headings(source.body)} — a section was dropped or invented`,
    );
  }
  const links = (s) => (s.match(/\]\(([^)]+)\)/g) || []).sort();
  if (JSON.stringify(links(translated.body)) !== JSON.stringify(links(source.body))) {
    problems.push("link targets changed");
  }
  if (!translated.body.includes("Universal Till")) {
    problems.push("the product name is missing — it must not be translated");
  }
  // Did it actually translate, or hand back English? Ask for the target
  // script rather than counting Latin characters — "Universal Till" is
  // supposed to stay Latin in every locale, which made the naive check fire
  // on a perfectly good Chinese title.
  const SCRIPT = { "zh-cn": /\p{Script=Han}/u, "fa-ir": /\p{Script=Arabic}/u };
  const expected = SCRIPT[locale];
  if (expected) {
    if (!expected.test(translated.title)) {
      problems.push("title is not in the target script — it came back untranslated");
    }
  } else if (translated.title === source.title) {
    // Every Latin-script locale (any LOCALES entry with no SCRIPT map entry —
    // tr-tr, de-de, and any future addition) needs this same fallback: a
    // same-script target can't be caught by a script regex, so an identical
    // title is the only cheap signal that the model handed back English
    // untranslated (ut-docs#871 — de-de shipped in #756 with no protection
    // at all, since this check used to be hardcoded to locale === "tr-tr").
    problems.push("title is identical to the English — it came back untranslated");
  }
  return problems;
}

// Parses an already-committed translated .mdx file the same way `main()`
// reads one off disk, then hands both sides to verify() unchanged. Split out
// so it's testable on in-memory strings without touching the filesystem.
function checkTranslation(source, locale, translatedRaw) {
  const { frontmatter, body } = splitFrontmatter(translatedRaw);
  const translated = {
    title: field(frontmatter, "title"),
    excerpt: field(frontmatter, "excerpt"),
    body,
  };
  return verify(source, translated, locale);
}

function main() {
  const sources = fs
    .readdirSync(path.join(BLOG, SOURCE_LOCALE))
    .filter((f) => f.endsWith(".mdx"))
    .filter((f) => !onlySlug || f === `${onlySlug}.mdx`);

  const targets = Object.keys(LOCALES).filter((l) => !onlyLocale || l === onlyLocale);

  let checked = 0;
  let failed = 0;

  for (const file of sources) {
    const raw = fs.readFileSync(path.join(BLOG, SOURCE_LOCALE, file), "utf8");
    const { frontmatter, body } = splitFrontmatter(raw);
    const source = {
      body,
      title: field(frontmatter, "title"),
      excerpt: field(frontmatter, "excerpt"),
    };

    for (const locale of targets) {
      const translatedPath = path.join(BLOG, locale, file);
      if (!fs.existsSync(translatedPath)) {
        console.log(`skip   ${locale}/${file} (not translated yet — falls back to English)`);
        continue;
      }

      process.stdout.write(`check  ${locale}/${file} … `);
      const problems = checkTranslation(source, locale, fs.readFileSync(translatedPath, "utf8"));
      checked++;
      if (problems.length) {
        console.log(`PROBLEM\n       ${problems.join("\n       ")}`);
        failed++;
      } else {
        console.log("ok");
      }
    }
  }

  console.log(`\n${checked} checked, ${failed} with problems.`);
  if (failed) process.exit(1);
}

// Only run the CLI when invoked directly (`node scripts/translate-posts.js`),
// not when imported — scripts/translate-posts_test.mjs imports `verify` and
// `checkTranslation` in isolation to regression-test the pure logic without
// touching the real blog content.
if (import.meta.url === `file://${process.argv[1]}`) {
  main();
}

export { verify, checkTranslation };
